import Head from 'next/head'
import Card from '@/components/Card'



export default function Home() {
  return (
    <>
      <Head>
      Frontend Mentor | QR code component
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card />
     
    </>
  )
}
